/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingRewardsSol from "./StakingRewards.sol";
export type { stakingRewardsSol };
import type * as mocks from "./mocks";
export type { mocks };
